APP_TITLE = "CUI-IP-ID (Phase 1)"
APP_VERSION = "1.0.0"
APP_DESCRIPTION = "CUI IP-ID Analysis and Reporting Tool"

MAX_DOC_CHARS=10000

OPENAI_MODEL = "gpt-4o-mini"
OPENAI_TIMEOUT_S = 60
OPENAI_MAX_OUTPUT_TOKENS = 1400
OPENAI_TEMPERATURE = 0.2